import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SmoothScrolling from "@/components/animations/SmoothScrolling";

const inter = Inter({ subsets: ["latin"] });
import {
  PoppinsFont,
  RobotoFont,
  DM_SansFont,
  OutfitFont,
  LatoFont,
  Plus_Jakarta_SansFont,
  ManropeFont,
} from "@/utils/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${PoppinsFont.className}`}><SmoothScrolling>{children}</SmoothScrolling></body>
    </html>
  );
}
