import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SmoothScrolling from "@/components/animations/SmoothScrolling";

const inter = Inter({ subsets: ["latin"] });
import {
  PoppinsFont,
  RobotoFont,
  DM_SansFont,
  OutfitFont,
  LatoFont,
  Plus_Jakarta_SansFont,
  ManropeFont,
} from "@/utils/fonts";
import { SizeProvider } from "@/contexts/sizeContext";
import Header from "@/components/header";
import Banner from "@/components/banner";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Dentist-Headless",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${PoppinsFont.className} relative`}>
        <div className="z-[999] relative">
          <Banner />
        </div>
        <div className="z-[999] sticky top-0 lg:relative">
          <Header />
        </div>
        <SmoothScrolling>{children}</SmoothScrolling>
        <div className="z-[999]">
          <Footer />
        </div>
      </body>
    </html>
  );
}
